# Generated by Django 4.2.23 on 2025-07-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_availdeadline_alter_user_availstart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Address',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
