# Generated by Django 4.2.23 on 2025-07-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ProfilePhoto',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/'),
        ),
    ]
